export enum AiTaskType {
  LEARNING_EVIDENCE = 'LEARNING_EVIDENCE',
  ASSESSMENT_GENERATOR = 'ASSESSMENT_GENERATOR',
  PROJECT_EVIDENCE = 'PROJECT_EVIDENCE',
  BEHAVIORAL_CAREER_ALIGNMENT = 'BEHAVIORAL_CAREER_ALIGNMENT',
}
