export enum AiTaskType {
  LEARNING_EVIDENCE = 'LEARNING_EVIDENCE',
  ASSESSMENT_GENERATOR = 'ASSESSMENT_GENERATOR',
  PROJECT_EVIDENCE = 'PROJECT_EVIDENCE',
  BEHAVIORAL_CAREER_ALIGNMENT = 'BEHAVIORAL_CAREER_ALIGNMENT',
  SKILL_INIT_CLASSIFICATION = 'SKILL_INIT_CLASSIFICATION',
  SKILL_INIT_ADAPTIVE_QUESTION = 'SKILL_INIT_ADAPTIVE_QUESTION',
  SKILL_INIT_SKILLS_EXPLANATOR = 'SKILL_INIT_SKILLS_EXPLANATOR',
  SKILL_TAXONOMY_RESOLVER = 'SKILL_TAXONOMY_RESOLVER',
  QUIZ_BATCH_EVALUATION = 'QUIZ_BATCH_EVALUATION',
}
